version: "3"
services:
  redis:
    image: redis

  gw:
    image: tykio/tyk-gateway:${tag}
    volumes:
      - ./foobar-plugin/foobar-plugin.so:/opt/tyk-gateway/middleware/foobar-plugin.so
      - ./helloworld-plugin/helloworld-plugin.so:/opt/tyk-gateway/middleware/helloworld-plugin.so
      - ./helloworld-plugin/helloworld-plugin-1.json:/opt/tyk-gateway/apps/helloworld-plugin-1.json
      - ./helloworld-plugin/helloworld-plugin-2.json:/opt/tyk-gateway/apps/helloworld-plugin-2.json
      - ./foobar-plugin/foobar-plugin-1.json:/opt/tyk-gateway/apps/foorbar-plugin-1.json
      - ./foobar-plugin/foobar-plugin-2.json:/opt/tyk-gateway/apps/foorbar-plugin-2.json
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - TYK_LOGLEVEL=debug