---
version: "3"

tasks:
  default:
    desc: "Run everything"
    cmds:
      - task: test
      - task: lint

  test:
    desc: "Run tests"
    cmds:
      - go fmt ./...
      - go test -count=1 ./...

  # lint target is run from CI
  lint:
    desc: "Ensure linter pass"
    cmds:
      - schema-gen extract -o - | schema-gen lint -i -

  deps:
    desc: "Update deps"
    cmds:
      - go install github.com/TykTechnologies/exp/cmd/schema-gen@main
