# Keep the docs on tyk-docs in sync with this branch's docs

name: Update Config docs

on:
  push:
    branches:
      - master
      - release-**
    paths:
      - config/config.go

jobs:
  sync:
    name: tyk-config-docs
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          repository: TykTechnologies/tyk-docs
          event-type: tyk-config-docs
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}","repo":"gateway","branch":"${{github.ref_name}}"}'
