# Keep the branch on tyk-analytics in sync with this branch

name: Update tyk-analytics branch

on:
  push:
    branches:
      - master
      - release-**
      - integration/**

jobs:
  sync:
    name: tyk-analytics
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          repository: TykTechnologies/tyk-analytics
          event-type: new-tyk
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          repository: TykTechnologies/tyk-sink
          event-type: new-tyk
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
